/**
 * DexpiProfileGenerator
 *
 * Walks an emitted DEXPI XML output, identifies every (class, property)
 * pair that does not resolve through the currently loaded schemas
 * (Process.xml + Core.xml + any already-loaded Profiles), and emits a
 * Profile XML in the DEXPI metamodel grammar that, when loaded back into
 * the registry, fills the gap.
 *
 * Output is *deterministic*: the same input produces byte-identical XML
 * across runs. Classes are sorted alphabetically; within each class
 * properties are sorted by (kind, name). No timestamps. This matters for
 * the round-trip integration test (which compares generator output to a
 * known reference) and for users who want to commit generated Profiles
 * to source control.
 *
 * Generated Profiles use the bpmn2dexpi-specific Profile-level marker
 *   <Profile mode="extend"> ... </Profile>
 * which signals the registry to merge the Profile's property declarations
 * into the existing classes by name (rather than reject as conflict). The
 * marker is documented as project-internal until DEXPI publishes a
 * standard Profile-extension idiom; see the registry source for migration
 * notes.
 *
 * Type inference is conservative: every DataProperty gets
 * Builtin/Undefined, every ReferenceProperty / CompositionProperty gets
 * Core/ConceptualObject (the abstract root from which every DEXPI object
 * type descends). Users wanting precise types should refine the
 * generated file by hand — a header comment on the output reminds them.
 */

import type { DexpiProcessClassRegistry } from './DexpiProcessClassRegistry';
import {
  validateEmittedDexpiXml,
  validateBpmnExtensionElements,
  type PropertyFailure,
  type PropertyKind,
} from './DexpiPropertyNameValidator';

export interface GenerateProfileResult {
  /** The generated Profile XML, ready to be written to disk or imported. */
  xml: string;
  /** Number of distinct (class, property) pairs the Profile declares. */
  declarations: number;
  /** Number of classes the Profile extends or adds. */
  classCount: number;
  /**
   * Number of iteration passes the generator needed to converge. 1 means
   * a single pass closed all gaps; higher values indicate that some
   * gaps only became visible after earlier-iteration declarations were
   * loaded into the intermediate registry (typical of deeply-nested
   * project extensions like PhysicalProperties → MolecularWeight).
   */
  iterationsUsed: number;
  /**
   * Human-readable warnings the generator wants the caller to surface in
   * the UI / CLI. Currently used for narrowing notices: when the user
   * marks a DEXPI-standard property as required, the Profile narrows
   * lower=0 → lower=1 and we emit one notice per affected (class,property)
   * pair so the user knows their override is in effect (and so reviewers
   * can audit the deviation).
   */
  warnings: string[];
}

const PROFILE_HEADER_COMMENT = `
  This DEXPI Profile was generated by bpmn2dexpi from a model that
  contained class/property pairs not declared in the loaded DEXPI 2.0
  schema (Process.xml + Core.xml). Loading this Profile alongside the
  source model closes the strict-mode property-name fidelity gap.

  Conventions used by the generator:

    - Profile-level mode="extend" marker: signals the registry to merge
      these property declarations into existing classes by name rather
      than reject the conflict. This marker is bpmn2dexpi-specific; when
      DEXPI publishes a standard Profile-extension idiom, regenerate.

    - Conservative type inference: DataProperty values are typed as
      Builtin/Undefined; ReferenceProperty / CompositionProperty targets
      are typed as Core/ConceptualObject (the abstract root). The
      generator cannot infer precise types from the model's runtime XML
      alone — refine by hand when the precise types matter to downstream
      consumers.

    - Deterministic ordering: classes alphabetical; properties within a
      class sorted by (kind, name). Same input -> byte-identical output.
`;

interface GeneratedProperty {
  name: string;
  kind: PropertyKind;
  /**
   * For data-kind properties: inferred Builtin type (e.g. 'Builtin/Double')
   * when the generator observed values and could derive a more-restrictive
   * type than the default Builtin/Undefined. Undefined when no inference
   * was possible.
   */
  inferredType?: string;
  /** Inferred lower-bound cardinality from observed counts (default: 0). */
  inferredLower?: number;
  /** Inferred upper-bound cardinality from observed counts. null = unbounded. */
  inferredUpper?: number | null;
  /**
   * For reference / composition kinds: inferred target class name (the
   * least-common-ancestor of all observed targets). Falls back to
   * Core/ConceptualObject (universal supertype) when inference fails.
   */
  inferredTargetClass?: string;
}

interface GeneratedClass {
  name: string;
  /** Properties to declare on this class, sorted by (kind, name). */
  properties: GeneratedProperty[];
  /**
   * Explicit supertype to emit on `<ConcreteClass superTypes="...">`. Populated
   * when the class originates from a Custom-typed BPMN annotation that carries
   * a user-chosen `customSuperType`. When omitted, the renderer falls back to
   * the class's existing supertype in the registry, or Core/ConceptualObject
   * if the class is not (yet) registered.
   */
  customSuperType?: string;
}

/**
 * Walk the emitted DEXPI XML (and optionally the source BPMN's extension
 * elements) and produce a deterministic Profile that fills every property-
 * name fidelity gap surfaced by the validator.
 *
 * Both paths are walked when bpmnXml is provided. The generator iterates
 * to a fixed point: each pass adds the latest layer of gaps to the
 * accumulated profile, then re-runs the validators against an
 * intermediate registry that includes the new declarations. This
 * captures deeply-nested project extensions (e.g. PhysicalProperties
 * containing MolecularWeight + LiquidDensity + ...) in a single
 * generator call rather than requiring users to regenerate manually
 * after each load.
 *
 * Convergence is guaranteed: each iteration adds at least one new
 * (class, property) pair or terminates. We cap at MAX_ITERATIONS as a
 * defense against malformed input, but in practice the TEP fixture
 * converges in 3 passes.
 *
 * Declarations are de-duplicated by (className, propertyName) — the
 * same gap may appear on both BPMN and emitted-XML sides for the same
 * model. When a pair appears on both sides with different inferred
 * kinds, the emitted-XML kind wins (carrier-element discrimination is
 * unambiguous; BPMN-side inference is heuristic).
 *
 * If the input has zero unresolved properties, the returned XML still
 * contains a valid (empty) Profile so callers can rely on having
 * something to write. declarations === 0 in that case.
 */
export function generateProfileFromDexpiXml(
  emittedXml: string,
  registry: DexpiProcessClassRegistry,
  options: { bpmnXml?: string } = {},
): GenerateProfileResult {
  // Hard cap on iterations. The TEP fixture converges in 3 passes; a
  // well-formed model should never need more than a handful. If we hit
  // this cap we throw rather than silently returning a partial profile —
  // a runaway loop would indicate either a generator bug or a deeply
  // pathological input that the user needs to inspect before shipping.
  const MAX_ITERATIONS = 10;
  // Accumulate per-class state across all iterations. Two surfaces feed in:
  //   - property failures from the validators (one entry per property)
  //   - custom-class declarations from BPMN dexpi:Element annotations
  //     where dexpiType is not in the registry (one entry per class, no
  //     properties, carrying the user-chosen customSuperType)
  // The same class may be touched by both surfaces — they merge by class
  // name, with property entries accumulating into properties[].
  const accumulated = new Map<string, AccumulatedClass>();

  // One-time pass: pick up Custom-typed BPMN elements (dexpiType ∉ registry)
  // and seed the accumulator with class-only entries. Subsequent iterations
  // of the property-failure loop run against an intermediate registry that
  // includes these declarations, so any properties used on the custom class
  // surface as ordinary failures and merge into the same class entry.
  if (options.bpmnXml) {
    seedFromCustomBpmnAnnotations(options.bpmnXml, registry, accumulated);
  }

  let workingRegistry = registry;
  // Merge the seeded custom classes into the working registry up front, so
  // the very first validator pass descends into their instances and surfaces
  // any property gaps.
  if (accumulated.size > 0) {
    const seedXml = renderFromAccumulated(accumulated, workingRegistry);
    workingRegistry = workingRegistry.cloneAndMergeXml('__intermediate__', seedXml);
  }
  let converged = false;
  let iterationsUsed = 0;
  for (let iter = 0; iter < MAX_ITERATIONS; iter++) {
    iterationsUsed = iter + 1;
    const emittedFailures = validateEmittedDexpiXml(emittedXml, '__generator__', workingRegistry);
    const bpmnFailures = options.bpmnXml
      ? validateBpmnExtensionElements(options.bpmnXml, '__generator__', workingRegistry)
      : [];
    const all = [...emittedFailures, ...bpmnFailures];
    let added = 0;
    for (const f of all) {
      if (!f.kind) continue;
      // Kind-mismatch failures (declaredKind set) report a property that IS
      // in the active vocabulary, just on a different carrier than the model
      // emitted/used it on — an authoring bug, not a vocabulary gap. The
      // Profile mechanism cannot legitimately re-declare an existing
      // property with a different kind, so these are skipped here.
      if (f.declaredKind !== undefined) continue;
      const cls = ensureAccumulatedClass(accumulated, f.className);
      if (!cls.properties.has(f.propertyName)) {
        cls.properties.set(f.propertyName, f.kind);
        added++;
      }
    }
    if (added === 0) {
      converged = true;
      break;
    }
    // Build the next iteration's working registry by merging the current
    // accumulated profile XML.
    const intermediate = renderFromAccumulated(accumulated, workingRegistry);
    workingRegistry = workingRegistry.cloneAndMergeXml('__intermediate__', intermediate);
  }
  if (!converged) {
    throw new Error(
      `DEXPI Profile generator did not converge within ${MAX_ITERATIONS} iterations. ` +
      `This indicates either a generator bug or a deeply pathological input. ` +
      `Inspect the source model for unbounded structural recursion before retrying.`
    );
  }

  // Inference passes — observe the emitted XML once more and derive
  // type / cardinality / target-class hints for every property we're
  // about to declare. Without these, the generator emits permissive
  // defaults (Builtin/Undefined, lower=0/upper=1, ConceptualObject) that
  // silence the strict-mode validators on subsequent runs. With them,
  // the validate→generate→reload→validate loop catches drift across
  // all five tiers.
  const inferredTypes = inferDataTypesFromValues(emittedXml, accumulated);
  const inferredCardinalities = inferCardinalitiesFromCounts(emittedXml, accumulated);
  const inferredTargets = inferTargetClassesFromObservedTargets(emittedXml, accumulated, registry);

  // Required-flag pass — narrow inferred lower=0 to lower=1 where the user
  // ticked "required" on the BPMN attribute. Narrow-only: never loosens
  // DEXPI's declarations. Returns warnings the caller can surface.
  const generatorWarnings: string[] = [];
  if (options.bpmnXml) {
    const requiredFlags = collectRequiredFlagsFromBpmn(options.bpmnXml, generatorWarnings);
    if (requiredFlags.size > 0) {
      applyRequiredFlagsToCardinalities(
        requiredFlags,
        inferredCardinalities,
        registry,
        generatorWarnings,
      );
    }
  }

  // One final render off the original (untouched) registry — that's the
  // registry the caller passed in, and the supertypes we report should
  // reference its classes, not intermediate ones.
  const xml = renderFromAccumulated(accumulated, registry, {
    types: inferredTypes,
    cardinalities: inferredCardinalities,
    targets: inferredTargets,
  });
  let propertyDeclarations = 0;
  for (const cls of accumulated.values()) propertyDeclarations += cls.properties.size;
  return {
    xml,
    declarations: propertyDeclarations,
    classCount: countClasses(accumulated),
    iterationsUsed,
    warnings: generatorWarnings,
  };
}

/**
 * Walk emittedXml and collect all `<Data property="X">value</Data>` text
 * values per (className, propertyName), where className is the wrapping
 * Object's bare type. For each (className, propertyName) we're about to
 * emit as a DataProperty, derive the most-restrictive Builtin type that
 * all observed values satisfy:
 *
 *   1. Builtin/Boolean   — every value is 'true'|'false'|'0'|'1'
 *   2. Builtin/Integer   — every value matches /^-?\d+$/
 *   3. Builtin/Double    — every value parses as a finite float
 *   4. Builtin/DateTime  — every value parses as ISO-8601
 *   5. Builtin/AnyURI    — every value matches a URI shape
 *   6. Builtin/String    — fallback (always passes)
 *
 * If we observe no values for the property (rare — would mean the
 * generator is emitting a property that never appears in the source XML),
 * we fall back to Builtin/String as the safest non-Undefined default.
 *
 * Returns a map keyed `${className}.${propertyName}` → inferred Builtin type.
 * Only DataProperty entries are inferred; ReferenceProperty / CompositionProperty
 * inference (target class) is out of scope for this pass.
 */
function inferDataTypesFromValues(
  emittedXml: string,
  accumulated: Map<string, AccumulatedClass>,
): Map<string, string> {
  const dataPropertyKeys = new Set<string>();
  for (const [, cls] of accumulated) {
    for (const [propName, kind] of cls.properties) {
      if (kind === 'data') dataPropertyKeys.add(`${cls.className}.${propName}`);
    }
  }
  if (dataPropertyKeys.size === 0) return new Map();

  // Walk emitted XML and collect values per (className, propertyName).
  // Cheap regex parse — no DOM dependency. Captures `<Data property="X">v</Data>`
  // and walks up to the nearest enclosing `<Object type="...">` to determine
  // the wrapping class.
  const observed = new Map<string, string[]>();
  const parser = new DOMParser();
  const doc = parser.parseFromString(emittedXml, 'text/xml');
  for (const dataEl of Array.from(doc.getElementsByTagName('Data')) as Element[]) {
    const propName = dataEl.getAttribute('property');
    if (!propName) continue;
    let parent: Element | null = dataEl.parentElement;
    while (parent && parent.tagName !== 'Object') parent = parent.parentElement;
    if (!parent) continue;
    const typeAttr = parent.getAttribute('type');
    if (!typeAttr) continue;
    const className = bareClassName(typeAttr);
    const key = `${className}.${propName}`;
    if (!dataPropertyKeys.has(key)) continue;
    const value = (dataEl.textContent ?? '').trim();
    if (value === '') continue;
    let arr = observed.get(key);
    if (!arr) {
      arr = [];
      observed.set(key, arr);
    }
    arr.push(value);
  }

  const inferred = new Map<string, string>();
  for (const key of dataPropertyKeys) {
    const values = observed.get(key);
    if (!values || values.length === 0) {
      inferred.set(key, 'Builtin/String'); // safe fallback
      continue;
    }
    inferred.set(key, inferBuiltinType(values));
  }
  return inferred;
}

/**
 * Pick the most-restrictive Builtin type that every value in the list
 * satisfies. Order is from most-restrictive to most-permissive.
 */
function inferBuiltinType(values: string[]): string {
  const allBoolean  = values.every(v => /^(true|false|0|1)$/.test(v));
  if (allBoolean) return 'Builtin/Boolean';
  const allInteger  = values.every(v => /^-?\d+$/.test(v));
  if (allInteger) return 'Builtin/Integer';
  const allDouble   = values.every(v => v !== '' && Number.isFinite(parseFloat(v)));
  if (allDouble) return 'Builtin/Double';
  const allDateTime = values.every(v => /^\d{4}-\d{2}-\d{2}/.test(v) && !Number.isNaN(Date.parse(v)));
  if (allDateTime) return 'Builtin/DateTime';
  const allUri      = values.every(v => /^[A-Za-z][A-Za-z0-9+.-]*:\S+/.test(v));
  if (allUri) return 'Builtin/AnyURI';
  return 'Builtin/String';
}

function bareClassName(typeRef: string): string {
  let s = typeRef;
  const lastSlash = s.lastIndexOf('/');
  if (lastSlash >= 0) s = s.slice(lastSlash + 1);
  const lastDot = s.lastIndexOf('.');
  if (lastDot >= 0) s = s.slice(lastDot + 1);
  return s;
}

/**
 * Walk emittedXml and observe, for each (className, propertyName) the
 * generator is about to declare, the per-Object occurrence count of that
 * property. Returns inferred upper-bound only:
 *
 *   - lower = always 0. Profiles follow DEXPI's permissive philosophy:
 *             they declare which properties MAY appear on instances, not
 *             which ones MUST. A user who wants a property to be required
 *             can opt in via the per-property required-flag UI (which the
 *             generator translates to lower=1 only when the user asks).
 *             Inferring lower=1 from "every observed instance happened to
 *             have this property" would overfit to a single corpus.
 *   - upper = max observed count if it's > 1; else 1. We do not infer
 *             unbounded (`null`) — strict consumers can interpret the
 *             literal `1` or larger and accept it as soft upper.
 *
 * If no Objects of that className are observed at all, the bounds entry
 * is omitted (renderer falls back to lower=0, upper=1).
 */
function inferCardinalitiesFromCounts(
  emittedXml: string,
  accumulated: Map<string, AccumulatedClass>,
): Map<string, { lower: number; upper: number | null }> {
  // Collect the set of (className, propertyName) we care about.
  const interestingKeys = new Set<string>();
  const propertiesByClass = new Map<string, Set<string>>();
  for (const [, cls] of accumulated) {
    const propSet = new Set<string>();
    for (const [propName] of cls.properties) {
      interestingKeys.add(`${cls.className}.${propName}`);
      propSet.add(propName);
    }
    propertiesByClass.set(cls.className, propSet);
  }
  if (interestingKeys.size === 0) return new Map();

  // For every relevant Object in the emitted XML, count occurrences of
  // each property among its DIRECT children. Track per-key:
  //   objectCount        — how many Objects of that class we saw
  //   timesPropertyAppears — for each prop name, the count summed
  //   minOccurrencesSeen — min count across observed Objects
  //   maxOccurrencesSeen — max count across observed Objects
  interface Tally {
    objectCount: number;
    minPerObject: number;
    maxPerObject: number;
  }
  const tallies = new Map<string, Tally>();

  const parser = new DOMParser();
  const doc = parser.parseFromString(emittedXml, 'text/xml');
  for (const obj of Array.from(doc.getElementsByTagName('Object'))) {
    const typeAttr = obj.getAttribute('type');
    if (!typeAttr) continue;
    const className = bareClassName(typeAttr);
    const propsToTrack = propertiesByClass.get(className);
    if (!propsToTrack || propsToTrack.size === 0) continue;

    // Count occurrences of each tracked property among DIRECT children.
    const perObject = new Map<string, number>();
    for (const child of Array.from(obj.children) as Element[]) {
      const tag = child.tagName;
      if (tag !== 'Data' && tag !== 'References' && tag !== 'Components') continue;
      const propName = child.getAttribute('property');
      if (!propName || !propsToTrack.has(propName)) continue;
      perObject.set(propName, (perObject.get(propName) ?? 0) + 1);
    }

    for (const propName of propsToTrack) {
      const key = `${className}.${propName}`;
      const count = perObject.get(propName) ?? 0;
      let t = tallies.get(key);
      if (!t) {
        t = { objectCount: 0, minPerObject: Number.POSITIVE_INFINITY, maxPerObject: 0 };
        tallies.set(key, t);
      }
      t.objectCount += 1;
      if (count < t.minPerObject) t.minPerObject = count;
      if (count > t.maxPerObject) t.maxPerObject = count;
    }
  }

  // Convert tallies → inferred bounds. lower is fixed at 0 (DEXPI flexibility:
  // Profiles declare optional surface area, not requirements; a user who
  // wants required cardinality opts in per-property via the required-flag
  // UI). upper is observed-max, floored at 1.
  const inferred = new Map<string, { lower: number; upper: number | null }>();
  for (const [key, t] of tallies) {
    if (t.objectCount === 0) continue; // no instances seen — leave default
    const upper = Math.max(1, t.maxPerObject);
    inferred.set(key, { lower: 0, upper });
  }
  return inferred;
}

/**
 * For each (className, propertyName) of kind=reference|composition, find
 * the least common ancestor of all observed target classes in the
 * registry's class hierarchy. Returns the inferred target class as a
 * bare name (renderer prefixes Core/ / /Process. as appropriate).
 *
 * Algorithm:
 *   1. Build id → class map across the document (one pass).
 *   2. For each `<References objects="..."/>` and `<ObjectReference object="..."/>`
 *      under a tracked (className, propertyName), collect the actual
 *      target class names.
 *   3. LCA across the supertype tree: for each class, build its full
 *      ancestor set (incl. self) via the registry; the LCA is the
 *      most-specific class present in EVERY ancestor set. Tie-break:
 *      pick the one most-specific class (closest to the actuals).
 *
 * Falls back to Core/ConceptualObject when:
 *   - No targets observed
 *   - Targets exist but their ancestor sets share only ConceptualObject
 *   - Registry can't compute ancestors for an unrecognised class
 */
function inferTargetClassesFromObservedTargets(
  emittedXml: string,
  accumulated: Map<string, AccumulatedClass>,
  registry: DexpiProcessClassRegistry,
): Map<string, string> {
  // Collect (className, propertyName) keys for ref + composition kinds.
  const interestingKeys = new Map<string, PropertyKind>();
  for (const [, cls] of accumulated) {
    for (const [propName, kind] of cls.properties) {
      if (kind === 'reference' || kind === 'composition') {
        interestingKeys.set(`${cls.className}.${propName}`, kind);
      }
    }
  }
  if (interestingKeys.size === 0) return new Map();

  // Pre-pass: build id → bare class name across the document.
  const parser = new DOMParser();
  const doc = parser.parseFromString(emittedXml, 'text/xml');
  const idToClass = new Map<string, string>();
  for (const obj of Array.from(doc.getElementsByTagName('Object'))) {
    const id = obj.getAttribute('id');
    const typeAttr = obj.getAttribute('type');
    if (id && typeAttr) idToClass.set(id, bareClassName(typeAttr));
  }

  // Collect observed target classes per key.
  const observed = new Map<string, Set<string>>();
  const recordTarget = (key: string, targetClass: string) => {
    let set = observed.get(key);
    if (!set) {
      set = new Set();
      observed.set(key, set);
    }
    set.add(targetClass);
  };

  // References carriers: <References property="X" objects="#a #b"/>.
  for (const refsEl of Array.from(doc.getElementsByTagName('References'))) {
    const propName = refsEl.getAttribute('property');
    const targetsAttr = refsEl.getAttribute('objects');
    if (!propName || !targetsAttr) continue;
    let parent: Element | null = refsEl.parentElement;
    while (parent && parent.tagName !== 'Object') parent = parent.parentElement;
    if (!parent) continue;
    const wrappingType = parent.getAttribute('type');
    if (!wrappingType) continue;
    const wrappingClass = bareClassName(wrappingType);
    const key = `${wrappingClass}.${propName}`;
    if (!interestingKeys.has(key)) continue;
    for (const t of targetsAttr.split(/\s+/).filter(Boolean)) {
      const id = t.startsWith('#') ? t.slice(1) : t;
      const cls = idToClass.get(id);
      if (cls) recordTarget(key, cls);
    }
  }

  // ObjectReference shells inside <Components>.
  for (const objRefEl of Array.from(doc.getElementsByTagName('ObjectReference'))) {
    const targetIdAttr = objRefEl.getAttribute('object');
    if (!targetIdAttr) continue;
    const targetId = targetIdAttr.startsWith('#') ? targetIdAttr.slice(1) : targetIdAttr;
    let parent: Element | null = objRefEl.parentElement;
    while (parent && parent.tagName !== 'Components') parent = parent.parentElement;
    if (!parent) continue;
    const propName = parent.getAttribute('property');
    if (!propName) continue;
    let outer: Element | null = parent.parentElement;
    while (outer && outer.tagName !== 'Object') outer = outer.parentElement;
    if (!outer) continue;
    const wrappingType = outer.getAttribute('type');
    if (!wrappingType) continue;
    const wrappingClass = bareClassName(wrappingType);
    const key = `${wrappingClass}.${propName}`;
    if (!interestingKeys.has(key)) continue;
    const cls = idToClass.get(targetId);
    if (cls) recordTarget(key, cls);
  }

  // Inline <Components><Object type="X">...</Object></Components>.
  for (const compsEl of Array.from(doc.getElementsByTagName('Components'))) {
    const propName = compsEl.getAttribute('property');
    if (!propName) continue;
    let outer: Element | null = compsEl.parentElement;
    while (outer && outer.tagName !== 'Object') outer = outer.parentElement;
    if (!outer) continue;
    const wrappingType = outer.getAttribute('type');
    if (!wrappingType) continue;
    const wrappingClass = bareClassName(wrappingType);
    const key = `${wrappingClass}.${propName}`;
    if (!interestingKeys.has(key)) continue;
    for (const inner of Array.from(compsEl.children) as Element[]) {
      if (inner.tagName !== 'Object') continue;
      const innerType = inner.getAttribute('type');
      if (!innerType) continue;
      recordTarget(key, bareClassName(innerType));
    }
  }

  // Compute LCA per key.
  const inferred = new Map<string, string>();
  for (const [key, classSet] of observed) {
    const lca = leastCommonAncestor(Array.from(classSet), registry);
    if (lca && lca !== 'ConceptualObject') {
      // Re-qualify with the source-file path (Process / Core).
      const info = registry.getClass(lca);
      if (info?.sourceFile === 'Process.xml') inferred.set(key, `/Process.${lca}`);
      else if (info?.sourceFile === 'Core.xml') inferred.set(key, `Core/${lca}`);
      else inferred.set(key, lca); // Profile-defined class — emit bare
    }
  }
  return inferred;
}

/**
 * Compute the least-common-ancestor of a set of class names in the
 * registry's supertype tree. Returns the most-specific common ancestor
 * (closest to the actuals); falls back to 'ConceptualObject' (universal
 * supertype) when no closer common ancestor exists.
 *
 * Each class's ancestor set is built by walking its `superTypes` chain
 * via the registry; the LCA is the intersection's most-specific class.
 */
function leastCommonAncestor(
  classes: string[],
  registry: DexpiProcessClassRegistry,
): string | null {
  if (classes.length === 0) return null;
  if (classes.length === 1) return classes[0];

  // Build ancestor set for each class (incl. self).
  const ancestors = classes.map(c => collectAncestors(c, registry));
  if (ancestors.some(s => s.size === 0)) return null;

  // Intersection of all ancestor sets.
  const common = new Set(ancestors[0]);
  for (let i = 1; i < ancestors.length; i++) {
    for (const c of common) {
      if (!ancestors[i].has(c)) common.delete(c);
    }
  }
  if (common.size === 0) return null;

  // Most-specific = the one whose own ancestor set is largest minus 1
  // (i.e., farthest from the universal root). Equivalently: the class
  // whose supertype chain has the most entries that are also in `common`.
  // Simpler heuristic: pick the class in `common` whose superTypes
  // (transitively) include all OTHER members of `common` — that's the
  // one closest to the actuals.
  let best: string | null = null;
  let bestRank = -1;
  for (const cand of common) {
    // Rank = depth in the supertype tree (deeper = more specific).
    const candAncestors = collectAncestors(cand, registry);
    const rank = candAncestors.size;
    if (rank > bestRank) {
      bestRank = rank;
      best = cand;
    }
  }
  return best;
}

function collectAncestors(
  className: string,
  registry: DexpiProcessClassRegistry,
): Set<string> {
  const seen = new Set<string>();
  const stack = [className];
  while (stack.length) {
    const cur = stack.pop()!;
    if (seen.has(cur)) continue;
    seen.add(cur);
    const info = registry.getClass(cur);
    if (info) {
      for (const sup of info.superTypes) stack.push(sup);
    }
  }
  return seen;
}

/**
 * Per-class accumulator entry. A class entry may exist with zero properties
 * — that's the case for Custom-typed BPMN annotations whose class-instance
 * carries no rich-DEXPI children. The renderer still emits a ConcreteClass
 * declaration so the round-trip Profile picks up the class identity.
 */
interface AccumulatedClass {
  className: string;
  /** Property name → kind, deduplicated. */
  properties: Map<string, PropertyKind>;
  /** User-chosen supertype from a Custom-typed BPMN annotation. Wins over
   *  the registry-derived supertype when the renderer emits the class. */
  customSuperType?: string;
}

function ensureAccumulatedClass(
  accumulated: Map<string, AccumulatedClass>,
  className: string,
): AccumulatedClass {
  let cls = accumulated.get(className);
  if (!cls) {
    cls = { className, properties: new Map() };
    accumulated.set(className, cls);
  }
  return cls;
}

/**
 * Walk BPMN extension elements for `<dexpi:element dexpiType="X" ...>` where
 * X is not (yet) a class in the registry. Each such element seeds an
 * accumulator entry recording the user-chosen supertype, so the generator
 * emits a ConcreteClass declaration for X. Properties used on instances of X
 * are picked up by the regular validator iteration once the seeded class is
 * merged into the working registry.
 */
function seedFromCustomBpmnAnnotations(
  bpmnXml: string,
  registry: DexpiProcessClassRegistry,
  accumulated: Map<string, AccumulatedClass>,
): void {
  // Cheap structural parse — no DOM dependency. The two attributes we need
  // (dexpiType, customSuperType) are deterministic in the dexpi: namespace.
  // We match either prefix-form or local-name to be tolerant of namespace
  // declaration variations.
  const elementRe = /<(?:[A-Za-z_][\w.-]*:)?element\b([^>]*)>/g;
  const dexpiTypeRe = /\bdexpiType\s*=\s*"([^"]*)"/;
  const customSuperRe = /\bcustomSuperType\s*=\s*"([^"]*)"/;
  let m: RegExpExecArray | null;
  while ((m = elementRe.exec(bpmnXml)) !== null) {
    const attrs = m[1];
    const tn = dexpiTypeRe.exec(attrs)?.[1];
    if (!tn) continue;
    if (registry.isValidClass(tn)) continue; // already declared — nothing to seed
    const sup = customSuperRe.exec(attrs)?.[1];
    const cls = ensureAccumulatedClass(accumulated, tn);
    if (sup && !cls.customSuperType) cls.customSuperType = sup;
  }
}

/**
 * Map a BPMN-side `<dexpi:stream streamType="...">` discriminator to the
 * DEXPI class the transformer emits for it. Mirrors
 * BpmnToDexpiTransformer.streamTypeToDexpiClass; kept in sync by hand
 * (small map, rarely changes — duplicating it avoids a dependency between
 * the generator and the transformer module).
 */
function streamTypeToDexpiClassName(streamType: string | null): string {
  switch (streamType) {
    case 'ThermalEnergyFlow':    return 'ThermalEnergyFlow';
    case 'MechanicalEnergyFlow': return 'MechanicalEnergyFlow';
    case 'ElectricalEnergyFlow': return 'ElectricalEnergyFlow';
    case 'EnergyFlow':           return 'EnergyFlow';
    case 'InformationFlow':      return 'InformationFlow';
    case 'MaterialFlow':
    case '':
    case null:
    default:                     return 'Stream';
  }
}

/**
 * Scan BPMN extension elements for user-asserted required-flagged attributes
 * and return a map of `${className}.${propertyName}` → `true`.
 *
 * Handled BPMN shapes (canonical-carrier form, all element kinds):
 *   <dexpi:element dexpiType="X">
 *     <dexpi:data property="P" required="true">v</dexpi:data>
 *     <dexpi:components property="P" required="true"> ... </dexpi:components>
 *     <dexpi:port portType="MaterialPort">
 *       <dexpi:data property="P" required="true">v</dexpi:data>
 *       <dexpi:components property="P" required="true"> ... </dexpi:components>
 *     </dexpi:port>
 *   </dexpi:element>
 *   <dexpi:Stream streamType="MaterialFlow">
 *     <dexpi:data property="P" required="true">v</dexpi:data>
 *     <dexpi:components property="P" required="true"> ... </dexpi:components>
 *   </dexpi:Stream>
 *
 * The className is taken from the wrapping `dexpiType` (for elements),
 * `streamType` via streamTypeToDexpiClassName (for streams), or `portType`
 * (for ports). In every case the override is per-class — a required flag
 * tightens the property only for that specific class, not its supertypes.
 *
 * The legacy `<dexpi:attribute name="P" required="true"/>` shape that
 * pre-#35 / #36 BPMN saves used is no longer scanned: the panel + transformer
 * dropped that read path together with the canonical-storage migration, so
 * any required-flag in that legacy shape was already invisible elsewhere
 * and would not round-trip into DEXPI export anyway.
 */
function collectRequiredFlagsFromBpmn(
  bpmnXml: string,
  warnings: string[],
): Map<string, Set<string>> {
  const result = new Map<string, Set<string>>();
  const parser = new DOMParser();
  const doc = parser.parseFromString(bpmnXml, 'text/xml');

  const recordRequired = (className: string, propName: string): void => {
    let set = result.get(className);
    if (!set) {
      set = new Set();
      result.set(className, set);
    }
    set.add(propName);
  };

  /**
   * Walk one DEXPI parent (`<dexpi:element>`, `<dexpi:Stream>`, or
   * `<dexpi:port>`) and record every direct-child carrier marked
   * required="true". Carrier kinds:
   *   - <dexpi:data property="X" required="true">v</dexpi:data>      (DataProperty)
   *   - <dexpi:components property="X" required="true">…</dexpi:components>  (CompositionProperty)
   *
   * Same name resolution across all carrier kinds: the `property` XML
   * attribute is the schema-declared property name. Carriers without
   * `required="true"` are ignored — only user-asserted overrides
   * propagate to the generated Profile.
   */
  const scanRequiredCarriers = (parent: Element, className: string): void => {
    for (const child of Array.from(parent.children) as Element[]) {
      const cln = (child.localName || '').toLowerCase();
      if (cln !== 'data' && cln !== 'components') continue;
      if (child.getAttribute('required') !== 'true') continue;
      const propName = child.getAttribute('property') || '';
      if (propName) recordRequired(className, propName);
    }
  };

  // Walk every <dexpi:element>, <dexpi:Stream>, and <dexpi:port> in document
  // order. A getElementsByTagName wildcard catches both prefixed and bare-
  // local-name forms; we filter on the local name to be namespace-prefix-
  // tolerant. Ports are walked independently of their wrapping element so
  // the per-port wrapping class (port.portType) is used for the override
  // — required flags on a MaterialPort attribute should only narrow
  // MaterialPort, not the wrapping ProcessStep.
  const candidates = Array.from(doc.getElementsByTagName('*'));
  for (const el of candidates) {
    const ln = (el.localName || '').toLowerCase();

    if (ln === 'element') {
      const className = el.getAttribute('dexpiType');
      if (!className) continue;
      scanRequiredCarriers(el, className);
      continue;
    }

    if (ln === 'stream') {
      const className = streamTypeToDexpiClassName(el.getAttribute('streamType'));
      scanRequiredCarriers(el, className);
      continue;
    }

    if (ln === 'port') {
      // portType on the port element identifies the wrapping class
      // (MaterialPort, ThermalEnergyPort, …). When portType is absent
      // we default to MaterialPort — same convention the rest of the
      // codebase uses (UI addPort, legacy migration, transformer
      // port reader). The warning surfaces in the generator's warnings
      // list so the user knows the default was applied; the required-
      // flag scan still runs against MaterialPort, so authored
      // overrides on these ports do reach the generated Profile.
      const portType = el.getAttribute('portType');
      const portIdLabel = el.getAttribute('portId') || el.getAttribute('id') || el.getAttribute('name') || '(unnamed)';
      const className = portType || 'MaterialPort';
      if (!portType) {
        warnings.push(
          `Port "${portIdLabel}" is missing portType — defaulted to MaterialPort for required-flag scan. ` +
          `Set portType explicitly on the port to remove this warning.`,
        );
      }
      scanRequiredCarriers(el, className);
      continue;
    }
  }

  return result;
}

/**
 * Apply user-asserted required flags to the inferred cardinalities map.
 * Narrow-only enforcement (Profiles can tighten DEXPI but never loosen it):
 *
 *   • Property in registry with declared lower=0 → narrow to lower=1.
 *     Emit a one-line warning so reviewers can audit the deviation.
 *   • Property in registry with declared lower≥1 → no-op.
 *     DEXPI already requires the property; nothing to override. No warning.
 *   • Property NOT in registry (custom property) → set lower=1 outright.
 *     Custom properties have no DEXPI-side default, so this is the only
 *     signal the generator has about required-cardinality intent.
 */
function applyRequiredFlagsToCardinalities(
  requiredFlags: Map<string, Set<string>>,
  cardinalities: Map<string, { lower: number; upper: number | null }>,
  registry: DexpiProcessClassRegistry,
  warnings: string[],
): void {
  for (const [className, propNames] of requiredFlags) {
    const declaredProps = registry.getProperties(className);
    for (const propName of propNames) {
      const declared = declaredProps.find(p => p.name === propName);
      const declaredLower = declared?.lower; // undefined when property is custom
      if (declaredLower !== undefined && declaredLower >= 1) continue; // already required by DEXPI
      const key = `${className}.${propName}`;
      const existing = cardinalities.get(key);
      const upper = existing?.upper ?? 1;
      cardinalities.set(key, { lower: 1, upper });
      if (declaredLower === 0) {
        warnings.push(
          `Required-flag override: ${className}.${propName} narrows DEXPI's declared ` +
          `lower=0 to lower=1 in the generated Profile. Profile-on-reload resolution ` +
          `rule: profile narrows DEXPI.`
        );
      }
      // declaredLower === undefined: custom property; no DEXPI to narrow, no warning.
    }
  }
}

/**
 * Bundle of all per-property inference hints applied during the final
 * render pass. Each map keys on `${className}.${propertyName}`.
 *
 *   types          — DataProperty inferred Builtin type
 *   cardinalities  — { lower, upper } observed counts on instances
 *   targets        — Reference / Composition inferred target class (LCA)
 */
interface InferenceHints {
  types?: Map<string, string>;
  cardinalities?: Map<string, { lower: number; upper: number | null }>;
  targets?: Map<string, string>;
}

function renderFromAccumulated(
  accumulated: Map<string, AccumulatedClass>,
  registry: DexpiProcessClassRegistry,
  hints?: InferenceHints,
): string {
  const classes: GeneratedClass[] = [];
  for (const cls of accumulated.values()) {
    const properties: GeneratedProperty[] = Array.from(cls.properties, ([name, kind]) => {
      const key = `${cls.className}.${name}`;
      const card = hints?.cardinalities?.get(key);
      return {
        name,
        kind,
        inferredType: hints?.types?.get(key),
        inferredLower: card?.lower,
        inferredUpper: card?.upper,
        inferredTargetClass: hints?.targets?.get(key),
      };
    });
    properties.sort(comparePropertyDecl);
    classes.push({ name: cls.className, properties, customSuperType: cls.customSuperType });
  }
  classes.sort((a, b) => a.name.localeCompare(b.name));
  return renderProfileXml(classes, registry);
}

function countClasses(accumulated: Map<string, AccumulatedClass>): number {
  return accumulated.size;
}

/**
 * Lower-level entry point — accept an already-computed failure list. Used
 * by callers that already ran validation and want to avoid a second walk
 * of the same XML.
 */
export function generateProfileFromFailures(
  failures: PropertyFailure[],
  registry: DexpiProcessClassRegistry,
): GenerateProfileResult {
  // Group by className → propertyName → kind (deduplicate exact repeats).
  // We use the FIRST kind seen per (class, property) pair; identical
  // properties never carry conflicting kinds in a well-formed DEXPI XML
  // (the carrier element type is structurally constrained).
  const byClass = new Map<string, Map<string, PropertyKind>>();
  for (const f of failures) {
    if (!f.kind) continue; // BPMN-side failures (no kind) are not generator input
    let cls = byClass.get(f.className);
    if (!cls) {
      cls = new Map();
      byClass.set(f.className, cls);
    }
    if (!cls.has(f.propertyName)) cls.set(f.propertyName, f.kind);
  }

  const classes: GeneratedClass[] = [];
  for (const [name, props] of byClass) {
    const properties = Array.from(props, ([n, k]) => ({ name: n, kind: k }));
    properties.sort(comparePropertyDecl);
    classes.push({ name, properties }); // customSuperType undefined: failures path doesn't see it
  }
  classes.sort((a, b) => a.name.localeCompare(b.name));

  const declarations = classes.reduce((n, c) => n + c.properties.length, 0);
  const xml = renderProfileXml(classes, registry);
  return { xml, declarations, classCount: classes.length, iterationsUsed: 1, warnings: [] };
}

function comparePropertyDecl(
  a: { name: string; kind: PropertyKind },
  b: { name: string; kind: PropertyKind },
): number {
  if (a.kind !== b.kind) return a.kind.localeCompare(b.kind);
  return a.name.localeCompare(b.name);
}

function renderProfileXml(
  classes: GeneratedClass[],
  registry: DexpiProcessClassRegistry,
): string {
  const lines: string[] = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push(`<!--${PROFILE_HEADER_COMMENT}-->`);
  lines.push('<Profile mode="extend" uri="https://bpmn2dexpi.local/profiles/generated">');
  for (const cls of classes) {
    lines.push(renderClassXml(cls, registry));
  }
  lines.push('</Profile>');
  lines.push(''); // trailing newline
  return lines.join('\n');
}

function renderClassXml(cls: GeneratedClass, registry: DexpiProcessClassRegistry): string {
  // Supertype resolution priority:
  //   1. customSuperType from a Custom-typed BPMN annotation (user's choice).
  //   2. The class's existing supertype in the registry (we're extending an
  //      already-declared class with new properties — preserve its parent).
  //   3. Core/ConceptualObject as the most permissive fallback for genuinely
  //      new classes the model used without prior declaration.
  let supertype: string;
  if (cls.customSuperType) {
    supertype = qualifyUserSupertype(cls.customSuperType, registry);
  } else {
    const info = registry.getClass(cls.name);
    if (info && info.superTypes.length > 0) {
      supertype = qualifySupertype(info.superTypes[0], registry);
    } else {
      supertype = 'Core/ConceptualObject';
    }
  }

  const lines: string[] = [];
  lines.push(`  <ConcreteClass name="${escAttr(cls.name)}" superTypes="${escAttr(supertype)}">`);
  for (const p of cls.properties) {
    lines.push(renderPropertyXml(p));
  }
  lines.push('  </ConcreteClass>');
  return lines.join('\n');
}

function renderPropertyXml(p: GeneratedProperty): string {
  // Cardinality bounds: prefer inferred values when available, default
  // to lower=0 / upper=1 (single-valued, optional). For Tier 5 fidelity:
  // when the generator observes the property always present, infers
  // lower=1; when observed multiple times, infers higher upper bound.
  const lower = p.inferredLower ?? 0;
  const upper = p.inferredUpper === null ? '*' : (p.inferredUpper ?? 1);
  // Note: the metamodel uses upper="*" for unbounded, but DEXPI's own
  // schema files use upper="*" only via a separate isOrdered/cardinality
  // form. The simplest serialization that round-trips through the
  // registry is to emit the numeric upper, omitting the attribute when
  // unbounded — but most strict consumers will accept upper="*". For
  // consistency we always emit numeric values; unbounded becomes
  // upper="*" only if explicitly set to null (rare in practice).
  const upperAttr = upper === '*' ? '*' : String(upper);

  switch (p.kind) {
    case 'data': {
      // Type inference: prefer the most-restrictive Builtin we observed
      // values fitting; fall back to Builtin/Undefined when the generator
      // had no value-level signal (intermediate registry-merge passes).
      const dataType = p.inferredType ?? 'Builtin/Undefined';
      return [
        `    <DataProperty name="${escAttr(p.name)}" lower="${lower}" upper="${upperAttr}">`,
        `      <DataTypeReference type="${escAttr(dataType)}"/>`,
        `    </DataProperty>`,
      ].join('\n');
    }
    case 'reference': {
      // Target inference: prefer the least-common-ancestor we computed
      // from observed targets; fall back to Core/ConceptualObject (the
      // universal supertype) when no targets were observed.
      const target = p.inferredTargetClass ?? 'Core/ConceptualObject';
      return [
        `    <ReferenceProperty name="${escAttr(p.name)}" lower="${lower}" upper="${upperAttr}">`,
        `      <ClassReference type="${escAttr(target)}"/>`,
        `    </ReferenceProperty>`,
      ].join('\n');
    }
    case 'composition': {
      const target = p.inferredTargetClass ?? 'Core/ConceptualObject';
      // CompositionProperty's upper attribute is also informative; emit
      // it for symmetry with reference/data even though Process.xml's own
      // CompositionProperty declarations omit it.
      return [
        `    <CompositionProperty name="${escAttr(p.name)}" lower="${lower}" upper="${upperAttr}">`,
        `      <ClassReference type="${escAttr(target)}"/>`,
        `    </CompositionProperty>`,
      ].join('\n');
    }
  }
}

/**
 * Re-qualify a bare class name to a name reference suitable for the
 * superTypes attribute. Uses the source-file label to decide between
 * '/Process.X' (Process.xml) and 'Core/X' (Core.xml or other). Profile-
 * declared classes use 'Core/ConceptualObject' as a permissive fallback
 * since their original namespace prefix isn't available here.
 */
function qualifySupertype(bareName: string, registry: DexpiProcessClassRegistry): string {
  const info = registry.getClass(bareName);
  if (!info) return `Core/ConceptualObject`;
  if (info.sourceFile === 'Process.xml') return `/Process.${bareName}`;
  if (info.sourceFile === 'Core.xml') return `Core/${bareName}`;
  return `Core/ConceptualObject`;
}

/**
 * Re-qualify a user-supplied supertype reference. The UI dropdown stores
 * bare class names (e.g. "ReactingChemicals") sourced from the same
 * registry passed to the generator, so a registry lookup gives us the
 * source-file label needed to qualify the reference. If the user-supplied
 * name does not resolve (e.g. they hand-edited the BPMN to point at an
 * undeclared class), fall back to Core/ConceptualObject so the generated
 * Profile is still loadable.
 */
function qualifyUserSupertype(userSuperType: string, registry: DexpiProcessClassRegistry): string {
  // Already a qualified reference (e.g. "Process/Process.X" or "Core/X")
  // — pass through verbatim.
  if (userSuperType.includes('/')) return userSuperType;
  return qualifySupertype(userSuperType, registry);
}

function escAttr(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
