/**
 * DexpiProfileGenerator
 *
 * Walks an emitted DEXPI XML output, identifies every (class, property)
 * pair that does not resolve through the currently loaded schemas
 * (Process.xml + Core.xml + any already-loaded Profiles), and emits a
 * Profile XML in the DEXPI metamodel grammar that, when loaded back into
 * the registry, fills the gap.
 *
 * Output is *deterministic*: the same input produces byte-identical XML
 * across runs. Classes are sorted alphabetically; within each class
 * properties are sorted by (kind, name). No timestamps. This matters for
 * the round-trip integration test (which compares generator output to a
 * known reference) and for users who want to commit generated Profiles
 * to source control.
 *
 * Generated Profiles use the bpmn2dexpi-specific Profile-level marker
 *   <Profile mode="extend"> ... </Profile>
 * which signals the registry to merge the Profile's property declarations
 * into the existing classes by name (rather than reject as conflict). The
 * marker is documented as project-internal until DEXPI publishes a
 * standard Profile-extension idiom; see the registry source for migration
 * notes.
 *
 * Type inference is conservative: every DataProperty gets
 * Builtin/Undefined, every ReferenceProperty / CompositionProperty gets
 * Core/ConceptualObject (the abstract root from which every DEXPI object
 * type descends). Users wanting precise types should refine the
 * generated file by hand — a header comment on the output reminds them.
 */

import type { DexpiProcessClassRegistry } from './DexpiProcessClassRegistry';
import {
  validateEmittedDexpiXml,
  validateBpmnExtensionElements,
  type PropertyFailure,
  type PropertyKind,
} from './DexpiPropertyNameValidator';

export interface GenerateProfileResult {
  /** The generated Profile XML, ready to be written to disk or imported. */
  xml: string;
  /** Number of distinct (class, property) pairs the Profile declares. */
  declarations: number;
  /** Number of classes the Profile extends or adds. */
  classCount: number;
  /**
   * Number of iteration passes the generator needed to converge. 1 means
   * a single pass closed all gaps; higher values indicate that some
   * gaps only became visible after earlier-iteration declarations were
   * loaded into the intermediate registry (typical of deeply-nested
   * project extensions like PhysicalProperties → MolecularWeight).
   */
  iterationsUsed: number;
}

const PROFILE_HEADER_COMMENT = `
  This DEXPI Profile was generated by bpmn2dexpi from a model that
  contained class/property pairs not declared in the loaded DEXPI 2.0
  schema (Process.xml + Core.xml). Loading this Profile alongside the
  source model closes the strict-mode property-name fidelity gap.

  Conventions used by the generator:

    - Profile-level mode="extend" marker: signals the registry to merge
      these property declarations into existing classes by name rather
      than reject the conflict. This marker is bpmn2dexpi-specific; when
      DEXPI publishes a standard Profile-extension idiom, regenerate.

    - Conservative type inference: DataProperty values are typed as
      Builtin/Undefined; ReferenceProperty / CompositionProperty targets
      are typed as Core/ConceptualObject (the abstract root). The
      generator cannot infer precise types from the model's runtime XML
      alone — refine by hand when the precise types matter to downstream
      consumers.

    - Deterministic ordering: classes alphabetical; properties within a
      class sorted by (kind, name). Same input -> byte-identical output.
`;

interface GeneratedClass {
  name: string;
  /** Properties to declare on this class, sorted by (kind, name). */
  properties: { name: string; kind: PropertyKind }[];
  /**
   * Explicit supertype to emit on `<ConcreteClass superTypes="...">`. Populated
   * when the class originates from a Custom-typed BPMN annotation that carries
   * a user-chosen `customSuperType`. When omitted, the renderer falls back to
   * the class's existing supertype in the registry, or Core/ConceptualObject
   * if the class is not (yet) registered.
   */
  customSuperType?: string;
}

/**
 * Walk the emitted DEXPI XML (and optionally the source BPMN's extension
 * elements) and produce a deterministic Profile that fills every property-
 * name fidelity gap surfaced by the validator.
 *
 * Both paths are walked when bpmnXml is provided. The generator iterates
 * to a fixed point: each pass adds the latest layer of gaps to the
 * accumulated profile, then re-runs the validators against an
 * intermediate registry that includes the new declarations. This
 * captures deeply-nested project extensions (e.g. PhysicalProperties
 * containing MolecularWeight + LiquidDensity + ...) in a single
 * generator call rather than requiring users to regenerate manually
 * after each load.
 *
 * Convergence is guaranteed: each iteration adds at least one new
 * (class, property) pair or terminates. We cap at MAX_ITERATIONS as a
 * defense against malformed input, but in practice the TEP fixture
 * converges in 3 passes.
 *
 * Declarations are de-duplicated by (className, propertyName) — the
 * same gap may appear on both BPMN and emitted-XML sides for the same
 * model. When a pair appears on both sides with different inferred
 * kinds, the emitted-XML kind wins (carrier-element discrimination is
 * unambiguous; BPMN-side inference is heuristic).
 *
 * If the input has zero unresolved properties, the returned XML still
 * contains a valid (empty) Profile so callers can rely on having
 * something to write. declarations === 0 in that case.
 */
export function generateProfileFromDexpiXml(
  emittedXml: string,
  registry: DexpiProcessClassRegistry,
  options: { bpmnXml?: string } = {},
): GenerateProfileResult {
  // Hard cap on iterations. The TEP fixture converges in 3 passes; a
  // well-formed model should never need more than a handful. If we hit
  // this cap we throw rather than silently returning a partial profile —
  // a runaway loop would indicate either a generator bug or a deeply
  // pathological input that the user needs to inspect before shipping.
  const MAX_ITERATIONS = 10;
  // Accumulate per-class state across all iterations. Two surfaces feed in:
  //   - property failures from the validators (one entry per property)
  //   - custom-class declarations from BPMN dexpi:Element annotations
  //     where dexpiType is not in the registry (one entry per class, no
  //     properties, carrying the user-chosen customSuperType)
  // The same class may be touched by both surfaces — they merge by class
  // name, with property entries accumulating into properties[].
  const accumulated = new Map<string, AccumulatedClass>();

  // One-time pass: pick up Custom-typed BPMN elements (dexpiType ∉ registry)
  // and seed the accumulator with class-only entries. Subsequent iterations
  // of the property-failure loop run against an intermediate registry that
  // includes these declarations, so any properties used on the custom class
  // surface as ordinary failures and merge into the same class entry.
  if (options.bpmnXml) {
    seedFromCustomBpmnAnnotations(options.bpmnXml, registry, accumulated);
  }

  let workingRegistry = registry;
  // Merge the seeded custom classes into the working registry up front, so
  // the very first validator pass descends into their instances and surfaces
  // any property gaps.
  if (accumulated.size > 0) {
    const seedXml = renderFromAccumulated(accumulated, workingRegistry);
    workingRegistry = workingRegistry.cloneAndMergeXml('__intermediate__', seedXml);
  }
  let converged = false;
  let iterationsUsed = 0;
  for (let iter = 0; iter < MAX_ITERATIONS; iter++) {
    iterationsUsed = iter + 1;
    const emittedFailures = validateEmittedDexpiXml(emittedXml, '__generator__', workingRegistry);
    const bpmnFailures = options.bpmnXml
      ? validateBpmnExtensionElements(options.bpmnXml, '__generator__', workingRegistry)
      : [];
    const all = [...emittedFailures, ...bpmnFailures];
    let added = 0;
    for (const f of all) {
      if (!f.kind) continue;
      // Kind-mismatch failures (declaredKind set) report a property that IS
      // in the active vocabulary, just on a different carrier than the model
      // emitted/used it on — an authoring bug, not a vocabulary gap. The
      // Profile mechanism cannot legitimately re-declare an existing
      // property with a different kind, so these are skipped here.
      if (f.declaredKind !== undefined) continue;
      const cls = ensureAccumulatedClass(accumulated, f.className);
      if (!cls.properties.has(f.propertyName)) {
        cls.properties.set(f.propertyName, f.kind);
        added++;
      }
    }
    if (added === 0) {
      converged = true;
      break;
    }
    // Build the next iteration's working registry by merging the current
    // accumulated profile XML.
    const intermediate = renderFromAccumulated(accumulated, workingRegistry);
    workingRegistry = workingRegistry.cloneAndMergeXml('__intermediate__', intermediate);
  }
  if (!converged) {
    throw new Error(
      `DEXPI Profile generator did not converge within ${MAX_ITERATIONS} iterations. ` +
      `This indicates either a generator bug or a deeply pathological input. ` +
      `Inspect the source model for unbounded structural recursion before retrying.`
    );
  }

  // One final render off the original (untouched) registry — that's the
  // registry the caller passed in, and the supertypes we report should
  // reference its classes, not intermediate ones.
  const xml = renderFromAccumulated(accumulated, registry);
  let propertyDeclarations = 0;
  for (const cls of accumulated.values()) propertyDeclarations += cls.properties.size;
  return {
    xml,
    declarations: propertyDeclarations,
    classCount: countClasses(accumulated),
    iterationsUsed,
  };
}

/**
 * Per-class accumulator entry. A class entry may exist with zero properties
 * — that's the case for Custom-typed BPMN annotations whose class-instance
 * carries no rich-DEXPI children. The renderer still emits a ConcreteClass
 * declaration so the round-trip Profile picks up the class identity.
 */
interface AccumulatedClass {
  className: string;
  /** Property name → kind, deduplicated. */
  properties: Map<string, PropertyKind>;
  /** User-chosen supertype from a Custom-typed BPMN annotation. Wins over
   *  the registry-derived supertype when the renderer emits the class. */
  customSuperType?: string;
}

function ensureAccumulatedClass(
  accumulated: Map<string, AccumulatedClass>,
  className: string,
): AccumulatedClass {
  let cls = accumulated.get(className);
  if (!cls) {
    cls = { className, properties: new Map() };
    accumulated.set(className, cls);
  }
  return cls;
}

/**
 * Walk BPMN extension elements for `<dexpi:element dexpiType="X" ...>` where
 * X is not (yet) a class in the registry. Each such element seeds an
 * accumulator entry recording the user-chosen supertype, so the generator
 * emits a ConcreteClass declaration for X. Properties used on instances of X
 * are picked up by the regular validator iteration once the seeded class is
 * merged into the working registry.
 */
function seedFromCustomBpmnAnnotations(
  bpmnXml: string,
  registry: DexpiProcessClassRegistry,
  accumulated: Map<string, AccumulatedClass>,
): void {
  // Cheap structural parse — no DOM dependency. The two attributes we need
  // (dexpiType, customSuperType) are deterministic in the dexpi: namespace.
  // We match either prefix-form or local-name to be tolerant of namespace
  // declaration variations.
  const elementRe = /<(?:[A-Za-z_][\w.-]*:)?element\b([^>]*)>/g;
  const dexpiTypeRe = /\bdexpiType\s*=\s*"([^"]*)"/;
  const customSuperRe = /\bcustomSuperType\s*=\s*"([^"]*)"/;
  let m: RegExpExecArray | null;
  while ((m = elementRe.exec(bpmnXml)) !== null) {
    const attrs = m[1];
    const tn = dexpiTypeRe.exec(attrs)?.[1];
    if (!tn) continue;
    if (registry.isValidClass(tn)) continue; // already declared — nothing to seed
    const sup = customSuperRe.exec(attrs)?.[1];
    const cls = ensureAccumulatedClass(accumulated, tn);
    if (sup && !cls.customSuperType) cls.customSuperType = sup;
  }
}

function renderFromAccumulated(
  accumulated: Map<string, AccumulatedClass>,
  registry: DexpiProcessClassRegistry,
): string {
  const classes: GeneratedClass[] = [];
  for (const cls of accumulated.values()) {
    const properties = Array.from(cls.properties, ([name, kind]) => ({ name, kind }));
    properties.sort(comparePropertyDecl);
    classes.push({ name: cls.className, properties, customSuperType: cls.customSuperType });
  }
  classes.sort((a, b) => a.name.localeCompare(b.name));
  return renderProfileXml(classes, registry);
}

function countClasses(accumulated: Map<string, AccumulatedClass>): number {
  return accumulated.size;
}

/**
 * Lower-level entry point — accept an already-computed failure list. Used
 * by callers that already ran validation and want to avoid a second walk
 * of the same XML.
 */
export function generateProfileFromFailures(
  failures: PropertyFailure[],
  registry: DexpiProcessClassRegistry,
): GenerateProfileResult {
  // Group by className → propertyName → kind (deduplicate exact repeats).
  // We use the FIRST kind seen per (class, property) pair; identical
  // properties never carry conflicting kinds in a well-formed DEXPI XML
  // (the carrier element type is structurally constrained).
  const byClass = new Map<string, Map<string, PropertyKind>>();
  for (const f of failures) {
    if (!f.kind) continue; // BPMN-side failures (no kind) are not generator input
    let cls = byClass.get(f.className);
    if (!cls) {
      cls = new Map();
      byClass.set(f.className, cls);
    }
    if (!cls.has(f.propertyName)) cls.set(f.propertyName, f.kind);
  }

  const classes: GeneratedClass[] = [];
  for (const [name, props] of byClass) {
    const properties = Array.from(props, ([n, k]) => ({ name: n, kind: k }));
    properties.sort(comparePropertyDecl);
    classes.push({ name, properties }); // customSuperType undefined: failures path doesn't see it
  }
  classes.sort((a, b) => a.name.localeCompare(b.name));

  const declarations = classes.reduce((n, c) => n + c.properties.length, 0);
  const xml = renderProfileXml(classes, registry);
  return { xml, declarations, classCount: classes.length, iterationsUsed: 1 };
}

function comparePropertyDecl(
  a: { name: string; kind: PropertyKind },
  b: { name: string; kind: PropertyKind },
): number {
  if (a.kind !== b.kind) return a.kind.localeCompare(b.kind);
  return a.name.localeCompare(b.name);
}

function renderProfileXml(
  classes: GeneratedClass[],
  registry: DexpiProcessClassRegistry,
): string {
  const lines: string[] = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push(`<!--${PROFILE_HEADER_COMMENT}-->`);
  lines.push('<Profile mode="extend" uri="https://bpmn2dexpi.local/profiles/generated">');
  for (const cls of classes) {
    lines.push(renderClassXml(cls, registry));
  }
  lines.push('</Profile>');
  lines.push(''); // trailing newline
  return lines.join('\n');
}

function renderClassXml(cls: GeneratedClass, registry: DexpiProcessClassRegistry): string {
  // Supertype resolution priority:
  //   1. customSuperType from a Custom-typed BPMN annotation (user's choice).
  //   2. The class's existing supertype in the registry (we're extending an
  //      already-declared class with new properties — preserve its parent).
  //   3. Core/ConceptualObject as the most permissive fallback for genuinely
  //      new classes the model used without prior declaration.
  let supertype: string;
  if (cls.customSuperType) {
    supertype = qualifyUserSupertype(cls.customSuperType, registry);
  } else {
    const info = registry.getClass(cls.name);
    if (info && info.superTypes.length > 0) {
      supertype = qualifySupertype(info.superTypes[0], registry);
    } else {
      supertype = 'Core/ConceptualObject';
    }
  }

  const lines: string[] = [];
  lines.push(`  <ConcreteClass name="${escAttr(cls.name)}" superTypes="${escAttr(supertype)}">`);
  for (const p of cls.properties) {
    lines.push(renderPropertyXml(p));
  }
  lines.push('  </ConcreteClass>');
  return lines.join('\n');
}

function renderPropertyXml(p: { name: string; kind: PropertyKind }): string {
  switch (p.kind) {
    case 'data':
      return [
        `    <DataProperty name="${escAttr(p.name)}" lower="0" upper="1">`,
        `      <DataTypeReference type="Builtin/Undefined"/>`,
        `    </DataProperty>`,
      ].join('\n');
    case 'reference':
      return [
        `    <ReferenceProperty name="${escAttr(p.name)}" lower="0" upper="1">`,
        `      <ClassReference type="Core/ConceptualObject"/>`,
        `    </ReferenceProperty>`,
      ].join('\n');
    case 'composition':
      return [
        `    <CompositionProperty name="${escAttr(p.name)}" lower="0">`,
        `      <ClassReference type="Core/ConceptualObject"/>`,
        `    </CompositionProperty>`,
      ].join('\n');
  }
}

/**
 * Re-qualify a bare class name to a name reference suitable for the
 * superTypes attribute. Uses the source-file label to decide between
 * '/Process.X' (Process.xml) and 'Core/X' (Core.xml or other). Profile-
 * declared classes use 'Core/ConceptualObject' as a permissive fallback
 * since their original namespace prefix isn't available here.
 */
function qualifySupertype(bareName: string, registry: DexpiProcessClassRegistry): string {
  const info = registry.getClass(bareName);
  if (!info) return `Core/ConceptualObject`;
  if (info.sourceFile === 'Process.xml') return `/Process.${bareName}`;
  if (info.sourceFile === 'Core.xml') return `Core/${bareName}`;
  return `Core/ConceptualObject`;
}

/**
 * Re-qualify a user-supplied supertype reference. The UI dropdown stores
 * bare class names (e.g. "ReactingChemicals") sourced from the same
 * registry passed to the generator, so a registry lookup gives us the
 * source-file label needed to qualify the reference. If the user-supplied
 * name does not resolve (e.g. they hand-edited the BPMN to point at an
 * undeclared class), fall back to Core/ConceptualObject so the generated
 * Profile is still loadable.
 */
function qualifyUserSupertype(userSuperType: string, registry: DexpiProcessClassRegistry): string {
  // Already a qualified reference (e.g. "Process/Process.X" or "Core/X")
  // — pass through verbatim.
  if (userSuperType.includes('/')) return userSuperType;
  return qualifySupertype(userSuperType, registry);
}

function escAttr(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
